#!/usr/bin/env bash

if [ -z "$HOME" ]; then echo "Seems you're \$HOMEless :("; exit 1; fi

DOTFILES=$HOME/.dotfiles
DOTFZF=$HOME/.fzf
DOTLOCAL=$HOME/.local/share/dotfiles

GITCLONE="git clone --depth=1"

cd "$HOME" || exit
rm -rf "$DOTFILES"
mkdir "$DOTFILES"
cd "$DOTFILES" || exit

git init
git remote add origin https://github.com/bthorne93/dotfiles.git
git pull origin master

# Swap origin so I can make edits easily
git remote rm origin
git remote add origin git@github.com:bthorne93/dotfiles.git

rm -rf \
  "$DOTFZF" \
  "$DOTLOCAL" \
  "$HOME/.bashrc" \
  "$HOME/.gitconfig" \
  "$HOME/.zshrc" \
  "$HOME/.emacs.d"

mkdir -p \
  "$DOTLOCAL" \
  "$HOME/.emacs.d"

ln -s "$DOTFILES/bashrc" "$HOME/.bashrc"
ln -s "$DOTFILES/gitconfig" "$HOME/.gitconfig"
ln -s "$DOTFILES/init.el" "$HOME/.emacs.d/init.el"
cp "$DOTFILES/config.org" "$HOME/.emacs.d/config.org"
ln -s "$DOTFILES/zshrc" "$HOME/.zshrc"

eval $GITCLONE https://github.com/cpaulik/emacs-material-theme "$HOME/.emacs.d/emacs-material-theme"
mv "$HOME/.emacs.d/emacs-material-theme/material-theme.el" "$HOME/.emacs.d/material-theme.el"

eval $GITCLONE https://github.com/junegunn/fzf.git "$DOTFZF"
"$DOTFZF/install" --key-bindings --completion --no-update-rc

ZSHPLUGS=(
  "zsh-completions"
  "zsh-history-substring-search"
  "zsh-syntax-highlighting"
)

#for INDEX in ${!ZSHPLUGS[*]}; do
#    echo $INDEX
#    echo $ZSHPLUGS
#    ZSHPLUG="${ZSHPLUGS[$INDEX]}"
#    eval $GITCLONE "https://github.com/zsh-users/$ZSHPLUG.git" "$DOTLOCAL/$ZSHPLUG"
#done

# The following assumes a conda installation. This is the standard code that would be installed
# by the conda installer during setup.
__conda_setup="$(CONDA_REPORT_ERRORS=false '/home/bthorne/anaconda3/bin/conda' shell.bash hook 2> /dev/null)"
if [ $? -eq 0 ]; then
    \eval "$__conda_setup"
else
    if [ -f "/home/bthorne/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/home/bthorne/anaconda3/etc/profile.d/conda.sh"
        CONDA_CHANGEPS1=false conda activate base
    else
        \export PATH="/home/bthorne/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup

cd "$HOME" || exit
rm -f "${HOME}/.zcompdump*"

echo
echo "DONEZO!!~!"
